title: Usman Ahmad # your name (or website title) here
logo: "/files/usman.jpg?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hello, my name is Usman Ahmad, and I'm machine learning and data science expert.
 I teach machine learning, emerging technologies and artificial intelligence courses at <a href= "https://bathspa.ae/"> Bath Spa University, UAE  </a> 
   </a> <br> <br>
 
 Keywords: 
 
 Machine Learning, 
 Computer Vision 
 & Medical Image Analysis
 

theme: jekyll-theme-minimal
