title: Usman Ahmad # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Meet Usman Ahmad, a keen researcher in the field of machine learning and artificial intelligence. I have made significant contributions to the development of cutting-edge AI technologies, including deep neural networks for classification and localization of images.
 <br><br>
  <a href="https://www.linkedin.com/in/usman-ahmad-005837140/">View My LinkedIn Profile</a> 
  

